#!/bin/bash

if [ -n "$1" ]; then
	cd $1
fi

if [ -z "$REGISTRY" ]; then
	REGISTRY="beta-registry.start9labs.com"
fi

git pull

VERSION=$(yq e ".version" manifest.yaml)
ID=$(yq e ".id" manifest.yaml)

make && ssh "root@${REGISTRY}" "mkdir -p /var/www/html/resources/apps/${ID}/${VERSION}" && scp "${ID}.s9pk" "root@${REGISTRY}:/var/www/html/resources/apps/${ID}/${VERSION}/${ID}.s9pk" && ssh "root@${REGISTRY}" reindex
