import { VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '0.21.1-beta:12',
  releaseNotes: {
    en_US: `Wallet migrations now work.

**Migrate from Umbrel and Migrate from StartOS were broken — they now run.** The SSH tools both imports rely on were missing from the service image, so every attempt failed on its first command. They are included now; the imports also stop the origin node and wait for it to fully shut down before copying (copying a live database yields a corrupt copy), verify the wallet actually arrived, and no longer clobber this package's managed configuration or TLS certificate with the origin's.

**New: Migrate Manually.** Coming from a platform without a built-in import (RaspiBlitz, myNode, a hand-rolled node)? Copy your old node's LND data directory onto this server yourself, then choose Migrate Manually under Initialize Wallet and enter your old wallet password. Data in LND's older database format is converted automatically on first start.

**Restoring a StartOS 0.3.5.x backup no longer leaves LND stuck at startup.** Those backups hold the wallet in LND's previous database format, and the one-time conversion to the current format only ran when a channel database was present — backups deliberately leave channel data out, because restoring stale channel state is dangerous. The conversion now also runs for a restored (or manually copied) wallet on its own; if your node has been stuck on "waiting on unlock-wallet", updating converts the wallet automatically on the next start, which may take a few minutes. Nothing was lost while it was stuck — the wallet was on disk the whole time, just unread.`,
    es_ES: `Las migraciones de monedero ahora funcionan.

**Migrar desde Umbrel y Migrar desde StartOS estaban rotas — ahora se ejecutan.** Las herramientas SSH de las que dependen ambas importaciones faltaban en la imagen del servicio, así que cada intento fallaba en su primer comando. Ahora están incluidas; además, las importaciones detienen el nodo de origen y esperan a que se apague por completo antes de copiar (copiar una base de datos en vivo produce una copia corrupta), verifican que el monedero realmente llegó, y ya no sobrescriben la configuración gestionada por este paquete ni su certificado TLS con los del origen.

**Nuevo: Migrar manualmente.** ¿Vienes de una plataforma sin importación integrada (RaspiBlitz, myNode, un nodo propio)? Copia tú mismo el directorio de datos de LND de tu antiguo nodo a este servidor, elige Migrar manualmente en Inicializar billetera e introduce la contraseña de tu antiguo monedero. Los datos en el formato de base de datos anterior de LND se convierten automáticamente en el primer arranque.

**Restaurar una copia de seguridad de StartOS 0.3.5.x ya no deja a LND atascado al arrancar.** Esas copias guardan el monedero en el formato de base de datos anterior de LND, y la conversión única al formato actual solo se ejecutaba si había una base de datos de canales presente — las copias de seguridad omiten deliberadamente los datos de canales, porque restaurar un estado de canal obsoleto es peligroso. La conversión ahora también se ejecuta para un monedero restaurado (o copiado manualmente) por sí solo; si tu nodo estaba atascado en «waiting on unlock-wallet», al actualizar se convertirá el monedero automáticamente en el siguiente arranque, lo que puede tardar unos minutos. No se perdió nada mientras estuvo atascado: el monedero estuvo siempre en el disco, solo que sin leerse.`,
    de_DE: `Wallet-Migrationen funktionieren jetzt.

**„Von Umbrel migrieren“ und „Von StartOS migrieren“ waren defekt — jetzt laufen sie.** Die SSH-Werkzeuge, auf die beide Importe angewiesen sind, fehlten im Dienst-Image, sodass jeder Versuch am ersten Befehl scheiterte. Sie sind jetzt enthalten; außerdem stoppen die Importe den Ursprungsknoten und warten, bis er vollständig heruntergefahren ist, bevor kopiert wird (das Kopieren einer laufenden Datenbank ergibt eine korrupte Kopie), prüfen, dass die Wallet wirklich angekommen ist, und überschreiben die von diesem Paket verwaltete Konfiguration und das TLS-Zertifikat nicht mehr mit denen des Ursprungs.

**Neu: Manuell migrieren.** Sie kommen von einer Plattform ohne eingebauten Import (RaspiBlitz, myNode, ein selbst aufgesetzter Knoten)? Kopieren Sie das LND-Datenverzeichnis Ihres alten Knotens selbst auf diesen Server, wählen Sie dann unter „Wallet initialisieren“ Manuell migrieren und geben Sie Ihr altes Wallet-Passwort ein. Daten im früheren Datenbankformat von LND werden beim ersten Start automatisch umgewandelt.

**Das Wiederherstellen einer StartOS-0.3.5.x-Sicherung lässt LND beim Start nicht mehr hängen.** Diese Sicherungen enthalten die Wallet im früheren Datenbankformat von LND, und die einmalige Umwandlung in das aktuelle Format lief nur, wenn eine Kanaldatenbank vorhanden war — Sicherungen lassen Kanaldaten bewusst weg, weil das Wiederherstellen veralteten Kanalzustands gefährlich ist. Die Umwandlung läuft nun auch für eine wiederhergestellte (oder manuell kopierte) Wallet allein; wenn Ihr Knoten bei „waiting on unlock-wallet“ feststeckte, wandelt das Update die Wallet beim nächsten Start automatisch um, was einige Minuten dauern kann. Während des Stillstands ging nichts verloren — die Wallet lag die ganze Zeit auf der Festplatte, nur ungelesen.`,
    pl_PL: `Migracje portfela teraz działają.

**„Migruj z Umbrel” i „Migruj z StartOS” były zepsute — teraz działają.** W obrazie usługi brakowało narzędzi SSH, na których opierają się oba importy, więc każda próba kończyła się niepowodzeniem na pierwszym poleceniu. Teraz są dołączone; importy dodatkowo zatrzymują węzeł źródłowy i czekają, aż całkowicie się wyłączy, zanim zaczną kopiować (kopiowanie działającej bazy danych daje uszkodzoną kopię), sprawdzają, czy portfel rzeczywiście dotarł, i nie nadpisują już konfiguracji zarządzanej przez ten pakiet ani jego certyfikatu TLS plikami ze źródła.

**Nowość: Migruj ręcznie.** Przechodzisz z platformy bez wbudowanego importu (RaspiBlitz, myNode, własny węzeł)? Skopiuj samodzielnie katalog danych LND ze starego węzła na ten serwer, następnie wybierz Migruj ręcznie w Zainicjalizuj portfel i podaj hasło starego portfela. Dane w starszym formacie bazy danych LND są konwertowane automatycznie przy pierwszym starcie.

**Przywrócenie kopii zapasowej ze StartOS 0.3.5.x nie zostawia już LND zablokowanego przy starcie.** Takie kopie zawierają portfel w poprzednim formacie bazy danych LND, a jednorazowa konwersja do obecnego formatu uruchamiała się tylko wtedy, gdy obecna była baza danych kanałów — kopie zapasowe celowo pomijają dane kanałów, ponieważ przywracanie nieaktualnego stanu kanału jest niebezpieczne. Konwersja uruchamia się teraz również dla samego przywróconego (lub ręcznie skopiowanego) portfela; jeśli twój węzeł utknął na „waiting on unlock-wallet”, aktualizacja przekonwertuje portfel automatycznie przy następnym starcie, co może potrwać kilka minut. Nic nie zostało utracone podczas tego zastoju — portfel przez cały czas był na dysku, tylko nieodczytany.`,
    fr_FR: `Les migrations de portefeuille fonctionnent désormais.

**« Migrer depuis Umbrel » et « Migrer depuis StartOS » étaient cassées — elles s'exécutent maintenant.** Les outils SSH dont dépendent les deux imports manquaient dans l'image du service, si bien que chaque tentative échouait dès la première commande. Ils sont désormais inclus ; les imports arrêtent en outre le nœud d'origine et attendent son arrêt complet avant de copier (copier une base de données en cours d'exécution produit une copie corrompue), vérifient que le portefeuille est bien arrivé, et n'écrasent plus la configuration gérée par ce paquet ni son certificat TLS avec ceux de l'origine.

**Nouveau : Migrer manuellement.** Vous venez d'une plateforme sans import intégré (RaspiBlitz, myNode, un nœud fait main) ? Copiez vous-même le répertoire de données LND de votre ancien nœud sur ce serveur, puis choisissez Migrer manuellement dans Initialiser le portefeuille et saisissez le mot de passe de votre ancien portefeuille. Les données dans l'ancien format de base de données de LND sont converties automatiquement au premier démarrage.

**Restaurer une sauvegarde StartOS 0.3.5.x ne laisse plus LND bloqué au démarrage.** Ces sauvegardes contiennent le portefeuille dans l'ancien format de base de données de LND, et la conversion unique vers le format actuel ne s'exécutait que si une base de données de canaux était présente — les sauvegardes excluent délibérément les données de canaux, car restaurer un état de canal obsolète est dangereux. La conversion s'exécute désormais aussi pour un portefeuille restauré (ou copié manuellement) seul ; si votre nœud était bloqué sur « waiting on unlock-wallet », la mise à jour convertira le portefeuille automatiquement au prochain démarrage, ce qui peut prendre quelques minutes. Rien n'a été perdu pendant ce blocage — le portefeuille est resté sur le disque tout du long, simplement non lu.`,
  },
  migrations: {},
})
